"use strict";
exports.__esModule = true;
var express_1 = require("express");
var app = (0, express_1["default"])();
app.set('view engine', 'ejs');
app.use(express_1["default"].static('../public'));
console.log('Running');
app.listen(process.env.PORT || 3000);
app.get('/', function (req, res) { return res.render('index.ejs'); });
app.get('/plans', function (req, res) { return res.render('pages/plans.ejs'); });
app.get('/addons', function (req, res) { return res.render('pages/addons.ejs'); });
app.get('/confirmation', function (req, res) { return res.render('pages/confirmation.ejs'); });
